# Generated by Django 4.2.13 on 2024-06-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='markdown',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Markdown'),
        ),
    ]
